name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.9'
            - name: Install
              run: npm i
            - name: Test and Coverage
              run: npm run test:ci

            - name: Update Coverage Badge
              if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              uses: we-cli/coverage-badge-action@main
